"""create subtraction table

Revision ID: 83d08a199b6e
Revises: f4f2cfe581de
Create Date: 2026-07-12 10:24:22.315534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '83d08a199b6e'
down_revision: Union[str, Sequence[str], None] = 'f4f2cfe581de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subtraction',
    sa.Column('subtraction_practice_id', sa.UUID(), nullable=False),
    sa.Column('questions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('score', sa.String(length=20), nullable=True),
    sa.Column('total_time_taken', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('subtraction_practice_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subtraction')
    # ### end Alembic commands ###
