"""create division table

Revision ID: dfd7ef0e7dfa
Revises: ddd128294f24
Create Date: 2026-07-12 12:01:10.951733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dfd7ef0e7dfa'
down_revision: Union[str, Sequence[str], None] = 'ddd128294f24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('division',
    sa.Column('division_practice_id', sa.UUID(), nullable=False),
    sa.Column('questions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('score', sa.String(length=20), nullable=True),
    sa.Column('total_time_taken', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('division_practice_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('division')
    # ### end Alembic commands ###
