"""add column score in addition table

Revision ID: f4f2cfe581de
Revises: bf8e77d6a31a
Create Date: 2026-07-12 02:08:55.990098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4f2cfe581de'
down_revision: Union[str, Sequence[str], None] = 'bf8e77d6a31a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addition', sa.Column('score', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('addition', 'score')
    # ### end Alembic commands ###
